# Generated by Django 4.2.4 on 2023-08-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclama',
            name='img',
            field=models.ImageField(blank=True, default='reclama/img.png', null=True, upload_to='reclama/', verbose_name='картинка рекламы'),
        ),
    ]
